#!/usr/bin/env ruby --disable-gems

require "tmpdir"

if ARGV.empty?
  # TODO: does this terminology make sense? probably not
  puts "Usage: specdiff [base-tree] <tree>"
  exit 1
end

if ARGV.size > 2
  puts "Don't know what you're doing"
  exit 1
end

base = ARGV.size == 2 ? ARGV.shift : "master"
tree = ARGV.shift

`git checkout #{base} > /dev/null 2>&1`

before = `SPEC_OPTS="--order defined --format documentation --no-color" bundle exec rake`

`git checkout #{tree} > /dev/null 2>&1`

after = `SPEC_OPTS="--order defined --format documentation --no-color" bundle exec rake`

`git checkout - > /dev/null 2>&1`

Dir.mktmpdir do |dir|
  Dir.chdir(dir)

  File.open("before.txt", "w") do |f|
    f.puts before
  end

  File.open("after.txt", "w") do |f|
    f.puts after
  end

  diff_command = ENV.fetch("DIFF", "diff")

  exec "#{diff_command} -U 3 before.txt after.txt"
end
